### ISSUE TITLE
PechaTool Rate-OCR

### ISSUE THREAD

**Issue by Tech-lo** [OpenPecha/Rate-OCR#1]
## Title
Pecha-tool-for-rate-ocr
## Description
We need a Pecha tool where a user can rate ocr image and transcript

## Expected UI
![Image](https://github.com/user-attachments/assets/d3f773c3-96de-4709-b261-6c687fb37fff)

## Sub-tasks

- [x] Create a remix app 
    - [x] UI Design and Implementation
- [x] make the connection with db using Prisma
- [x] Define Prisma models for OCR data and User
- [x] generate loader and pass initial annotator data from it to the UI
- [x] generate action to get data from inputs and update it on the database
- [x] Make a sidebar to view the history of work done by annotators and reviewers
- [x] user list in admin needs role changing option 
- [x] reviewer UI (same as annotator but except with editing , only approve and reject)

extra note:
user should be able to log in by going to /?session={email}
eg.   http://localhost:8000/?session=tashi@gmail.com

## Card reviewer
- [x] @tentamdin

**Comment by tentamdin** [comment]
More requirement from tenkal

- [x] data upload for admin (csv or json)
- [x] update schema

**Comment by Tech-lo** [comment]
Doc for Deploy Remix App created.  [In this repo's wiki](https://github.com/OpenPecha/pecha-tools-landing-page)
@tentamdin
